name: PythonActions
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: "ubuntu-18.04"
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Install conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: ysyl
        environment-file: environment.yml
        use-only-tar-bz2: true
        auto-activate-base: false
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        pytest
